package com.mycompany.gforcecalculator;

import java.awt.event.KeyEvent;
import java.util.ArrayList;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ruzte
 */
public class CalculatorFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculatorFrame.class.getName());
    /**
     * Creates new form CalculatorFrame
     */
    
    Calculation radious = new Calculation(1,"radious"); 
    Calculation Avelocity = new Calculation(2, "Avelocity"); 
    Calculation Tvelocity = new Calculation(3, "Tvelocity"); 
    Calculation Cacceleration = new Calculation(4, "Cacceleration"); 
    ArrayList<Calculation> list = new ArrayList<>(4); 
    public CalculatorFrame() {
        initComponents();
        
       
      
    }
    private void updateList(Calculation object, ArrayList<Calculation> list){
        list.remove(object); 
        list.add(object);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRadius = new javax.swing.JTextField();
        txtAV = new javax.swing.JTextField();
        txtTV = new javax.swing.JTextField();
        txtCA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcutor");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        txtRadius.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRadiusFocusGained(evt);
            }
        });

        txtAV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAVFocusGained(evt);
            }
        });

        txtTV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTVFocusGained(evt);
            }
        });

        txtCA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCAFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCA)
                    .addComponent(txtTV)
                    .addComponent(txtAV)
                    .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(txtAV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(txtTV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(txtCA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRadiusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRadiusFocusGained
        updateList(radious, list);
        try{
            for(Calculation calculation: list){
                System.out.println(calculation.getName());
            }
            System.out.println("///");
        } catch(ArrayIndexOutOfBoundsException exception){
            
        }
    }//GEN-LAST:event_txtRadiusFocusGained

    private void txtAVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAVFocusGained
        updateList(Avelocity, list);
        try{
            for(Calculation calculation: list){
                System.out.println(calculation.getName());
            }
            System.out.println("///");
        } catch(ArrayIndexOutOfBoundsException exception){
            
        }
    }//GEN-LAST:event_txtAVFocusGained

    private void txtTVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTVFocusGained
        updateList(Tvelocity, list);
        try{
            for(Calculation calculation: list){
                System.out.println(calculation.getName());
            }
            System.out.println("///");
        } catch(ArrayIndexOutOfBoundsException exception){
            
        }
        
    }//GEN-LAST:event_txtTVFocusGained

    private void txtCAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCAFocusGained
        updateList(Cacceleration, list);
        try{
            for(Calculation calculation: list){
                System.out.println(calculation.getName());
            }
            System.out.println("///");
        } catch(ArrayIndexOutOfBoundsException exception){
            
        }
    }//GEN-LAST:event_txtCAFocusGained

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getID() == KeyEvent.VK_ENTER){
            //calculate
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new CalculatorFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtAV;
    private javax.swing.JTextField txtCA;
    private javax.swing.JTextField txtRadius;
    private javax.swing.JTextField txtTV;
    // End of variables declaration//GEN-END:variables
}
