package com.mycompany.gforcecalculator;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.KeyStroke;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ruzte
 */
public class CalculatorFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculatorFrame.class.getName());
    /**
     * Creates new form CalculatorFrame
     */

    Calculation radious = new Calculation("radious");
    Calculation Avelocity = new Calculation("Avelocity");
    Calculation Tvelocity = new Calculation("Tvelocity");
    Calculation Cacceleration = new Calculation("Cacceleration");
    ArrayList<Calculation> list = new ArrayList<>(4);
    Calculator calculator = Calculator.getInstance();

    public CalculatorFrame() {
        initComponents();
        lblAV.setText("Angular Velocity (rad/sec)");
        lblRadious.setText("Radius (meters)");
        lblTV.setText("Tangential Velocity (meters/sec)");
        lblCA.setText("Centripetal Acceleration (g)");
        radious.setValue(txtRadius2);
        Avelocity.setValue(AV);
        Tvelocity.setValue(txtTV);
        Cacceleration.setValue(txtCA);
        updateFields();
        getKeyBinding();
    }

    private void updateList(Calculation object, ArrayList<Calculation> list){
        list.remove(object);
        list.add(object);
    }

    private void updateFields() {
        txtRadius2.setText("" + calculator.get('r'));
        txtTV.setText("" + calculator.get('v'));
        txtCA.setText("" + calculator.get('a'));
        AV.setText("" + calculator.get('w'));
    }

    Action enterAction = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            JTextField source = list.getLast().getValue();

            double dbl;

            try {
                dbl = Double.parseDouble(source.getText());
            }
            catch (NumberFormatException exception) {
                dbl = 0;
            }

            if (source == txtRadius2) {
                calculator.set('r', dbl);
            }
            else if (source == txtTV) {
                calculator.set('v', dbl);
            }
            else if (source == txtCA) {
                calculator.set('a', dbl);
            }
            else if (source == AV) {
                calculator.set('w', dbl);
            }

            updateFields();
        }
    };

    private void getKeyBinding(){
        InputMap iMap = getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap aMap = getRootPane().getActionMap();
        iMap.put(KeyStroke.getKeyStroke("ENTER"), "enter");
        aMap.put("enter", enterAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImgRadious2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        AV = new javax.swing.JTextField();
        txtTV = new javax.swing.JTextField();
        lblTV = new javax.swing.JLabel();
        lblCA = new javax.swing.JLabel();
        lblAV = new javax.swing.JLabel();
        lblRadious = new javax.swing.JLabel();
        txtCA = new javax.swing.JTextField();
        txtRadius2 = new javax.swing.JTextField();

        lblImgRadious2.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcutor");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        AV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AVFocusGained(evt);
            }
        });

        txtTV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTVFocusGained(evt);
            }
        });

        lblTV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblCA.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblAV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblAV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblRadious.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblRadious.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtCA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCAFocusGained(evt);
            }
        });

        txtRadius2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRadius2FocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(lblAV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRadious, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRadius2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(AV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCA))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRadious, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(txtRadius2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(lblTV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtTV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCA, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCA, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //focus ile hangisinin seçildiğini buluyor
    private void AVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AVFocusGained
        updateList(Avelocity, list);
    }//GEN-LAST:event_AVFocusGained

    private void txtTVFocusGained(java.awt.event.FocusEvent evt) {                                   
        updateList(Tvelocity, list);
    }                                 

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void txtCAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCAFocusGained
        updateList(Cacceleration, list);
    }//GEN-LAST:event_txtCAFocusGained

    private void txtRadius2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRadius2FocusGained
       updateList(radious, list);
    }//GEN-LAST:event_txtRadius2FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculatorFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAV;
    private javax.swing.JLabel lblCA;
    private javax.swing.JLabel lblImgRadious2;
    private javax.swing.JLabel lblRadious;
    private javax.swing.JLabel lblTV;
    private javax.swing.JTextField txtCA;
    private javax.swing.JTextField txtRadius2;
    private javax.swing.JTextField txtTV;
    // End of variables declaration//GEN-END:variables
}
